'use strict';

/**
 * build-facts.js - regenerate renderer/facts.js from the per-language source
 * lists in facts-src/ (one fact per line, plain UTF-8 text, no em dashes in
 * en/fi). Run: `node scripts/build-facts.js`.
 *
 * The client supplies ~500 facts per language; drop a new language's list in
 * facts-src/<lang>.txt and add it to LANGS below. A language with no list
 * falls back to English at runtime (see newtab.js).
 */

const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, '..', 'facts-src');
const OUT = path.join(__dirname, '..', 'renderer', 'facts.js');
const LANGS = ['en', 'fi', 'ru', 'es'];

function load(lang) {
  const file = path.join(SRC, lang + '.txt');
  if (!fs.existsSync(file)) return [];
  return fs.readFileSync(file, 'utf8')
    .split(/\r?\n/)
    .map((s) => s.replace(/^\s*\d+\.\s*/, '').trim())               // strip optional "N. "
    .map((s) => s.replace(/\s+(In English|Suomen kielen oma)\.?\s*$/i, '').trim())
    .filter(Boolean);
}

const data = {};
for (const lang of LANGS) data[lang] = load(lang);

const header =
  "'use strict';\n" +
  '// Fun facts by language. GENERATED by scripts/build-facts.js from facts-src/.\n' +
  '// Do not hand-edit; edit the source lists and re-run the builder.\n';

fs.writeFileSync(OUT, header + 'window.__EPHEMERA_FACTS = ' + JSON.stringify(data) + ';\n', 'utf8');
console.log('facts.js written:', LANGS.map((l) => `${l}=${data[l].length}`).join(' '));
